jobs:
  - name: runSh-Job-N
    type: runSh
    steps:
      - TASK:
        - script: export KEY=value
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: echo "prinitng KEY"
        - echo $KEY
    on_success:
      - script: echo "successfully completed"
