jobs:
  - name: trigger_center
    type: manifest
    steps:
      - IN: nginx_image
 
  - name: sample_node_runCI
    type: runCI
    steps:
      - IN: image_INs    

  - name: unhooked_project_runCI
    type: runCI
    steps:
      - IN: trigger_center
      - IN: sample_node_runCI
