jobs:
  - name: trigger_runSh_4
    type: manifest
    steps:
      - IN: nginx_image
    flags:
      - trigger_runSh_4      

  - name: trigger_runSh_0
    type: manifest
    steps:
      - IN: nginx_image

  - name: trigger_runSh_1
    type: manifest
    steps:
      - IN: nginx_image
    flags:
      - trigger_runSh_1  

  - name: trigger_runSh_2
    type: manifest
    steps:
      - IN: nginx_image
    flags:
      - trigger_runSh_2

  - name: runSh_0
    type: runSh
    steps:
      - IN: trigger_runSh_0
      - IN: nginx_image_1
      - TASK:
        - script: sleep 60
    flags:
      - runSh_0

  - name: runSh_1
    type: runSh
    steps:
      - IN: trigger_runSh_1
      - IN: nginx_image_2
      - IN: runSh_0
      - TASK:
        - script: sleep 60
    flags:
      - runSh_1

  - name: runSh_2
    type: runSh
    steps:
      - IN: trigger_runSh_2
      - IN: nginx_image_3
      - IN: runSh_1
      - TASK:
        - script: sleep 60
    flags:
      - runSh_2
