jobs:
  - name: trigger_runSh
    type: manifest
    steps:
      - IN: nginx_image

#  - name: sample_java_runCI
#    type: runCI
#    steps:
#      - IN: nginx_image
#    flags:
#      - test_1
#      - test_2
