jobs: 
  - name: runSh_1a
    type: runSh
    steps:
      - IN: nginx-image-11
      - TASK:
        - script: sleep 10
    on_success:
      - script: echo "successfully completed"      

  - name: runSh_1b
    type: runSh
    steps:
      - IN: runSh_1a
      - TASK:
        - script: sleep 10
    on_success:
      - script: echo "successfully completed"    
      
  - name: runSh_1c
    type: runSh
    steps:
      - IN: runSh_1b
      - TASK:
        - script: sleep 10
    on_success:
      - script: echo "successfully completed"      
      
  - name: runSh_2a
    type: runSh
    steps:
      - IN: nginx-image-11
      - TASK:
        - script: sleep 10
    on_success:
      - script: echo "successfully completed"      

  - name: runSh_2b
    type: runSh
    steps:
      - IN: runSh_2a
      - TASK:
        - script: sleep 10
    on_success:
      - script: echo "successfully completed"   
      
  - name: runSh_3a
    type: runSh
    steps:
      - IN: nginx-image-11
      - TASK:
        - script: sleep 10
    on_success:
      - script: echo "successfully completed"      

  - name: runSh_3b
    type: runSh
    steps:
      - IN: runSh_3a
      - TASK:
        - script: sleep 10
    on_success:
      - script: echo "successfully completed"      
      
  - name: runSh_4a
    type: runSh
    steps:
      - IN: nginx-image-11
      - TASK:
        - script: sleep 10
    on_success:
      - script: echo "successfully completed"      

  - name: runSh_4b
    type: runSh
    steps:
      - IN: runSh_4a
      - TASK:
        - script: sleep 10
    on_success:
      - script: echo "successfully completed"         
