jobs:
  - name: manifest_test_1
    type: manifest
    steps:
      - IN: success_manifest

  - name: manifest_test_2
    type: manifest
    steps:
      - IN: inconsistent_manifest 
      - IN: success_manifest
