jobs:
  - name: nginx-manifest
    type: manifest
    steps:
      - IN: nginx-image
      - TASK: managed

  - name: sample_node_runCI
    type: runCI
    steps:
      - IN: nginx-manifest
    flags: some_random_runCI
