jobs:
  - name: man-prod9
    type: manifest
    steps:
      - IN: nginx-prod9
      - TASK: managed

  - name: man-prod11
    type: manifest
    steps:
      - IN: nginx-prod11
      - TASK: managed

  - name: ddc
    type: deploy
    method: upgrade
    workflow: serial
    steps:
      - IN: man-prod9
      - IN: man-prod11
      - IN: ddc-cluster
      - TASK: managed
        #deployMethod: replace
        #deployOptions: 
          #- parallel


resources:
  - name: nginx-prod11
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.11

  - name: nginx-prod9
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.9

  - name: ddc-cluster
    type: cluster
    integration: "ddc-subint"
    pointer:
      sourceName: "ddc-cluster"
