jobs:
  - name: runSh_random
    type: runSh
    steps:
      - TASK:
        - script: sleep 1
        - script: sleep 2
    on_success:
      - script: echo "successfully completed"   
 
  - name: runSh_INs
    type: runSh
    steps:
      - TASK:
        - script: sleep 1
        - script: sleep 2
    on_success:
      - script: echo "successfully completed"   
   
  - name: runSh_OUTs
    type: runSh
    steps:
      - TASK:
        - script: sleep 2
    on_success:
      - script: echo "successfully completed"      
      
  - name: runSh_left
    type: runSh
    steps:
      - IN: runSh_INs
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 60
    on_success:
      - script: echo "successfully completed"      

  - name: runSh_center
    type: runSh
    steps:
      - IN: runSh_left
      - IN: sample_node_runCI
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 60
    on_success:
      - script: echo "successfully completed"    

  - name: runSh_right
    type: runSh
    steps:
      - IN: runSh_OUTs
      - IN: runSh_center
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 60
    on_success:
      - script: echo "successfully completed"  

  - name: sample_java_runCI
    type: runCI
    steps:
      - IN: runSh_OUTs
      - IN: runSh_center
 
   - name: sample_node_runCI
    type: runCI
    steps:
      - IN: runSh_INs

  - name: runSh_verify_commit_message
    type: runSh
    steps:
      - IN: pipelines_dry_run_gitRepo
      - OUT: pipelines_dry_run_ciRepo
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 6
    on_success:
      - script: echo "successfully completed"    
      
  - name: runSh_A
    type: runSh
    steps:
      - TASK:
        - script: sleep 1
    on_success:
      - script: echo "successfully completed"  
      
  - name: runSh_B
    type: runSh
    steps:
      - IN: runSh_A
      - TASK:
        - script: sleep 1
    on_success:
      - script: echo "successfully completed"          
