jobs:
  - name: trigger_center
    type: manifest
    steps:
      - IN: nginx_image

  - name: trigger_2
    type: manifest
    steps:
      - IN: nginx_image

  - name: sample_node_runCI
    type: runCI
    steps:
      - IN: image_INs
      - IN: trigger_center      

  - name: unhooked_project_runCI
    type: runCI
    steps:
      - IN: trigger_2
      - IN: sample_node_runCI
