jobs:
  - name: trigger_runCI_0
    type: manifest
    steps:
      - IN: nginx_image

  - name: trigger_runCI_1
    type: manifest
    steps:
      - IN: nginx_image

  - name: trigger_runCI_2
    type: manifest
    steps:
      - IN: nginx_image

  - name: sample_node_runCI
    type: runCI
    steps:
      - IN: trigger_runCI_0
    flags: runCI_sample_node_flag

  - name: unhooked_project_runCI
    type: runCI
    steps:
      - IN: trigger_runCI_1

  - name: sample_java_runCI
    type: runCI
    steps:
      - IN: trigger_runCI_2
      
  - name: matrix_test
    type: manifest
    steps:
      - IN: nginx_image
      - IN: sample_java_runCI

  - name: trigger_runSh_0
    type: manifest
    steps:
      - IN: nginx_image

  - name: trigger_runSh_1
    type: manifest
    steps:
      - IN: nginx_image

  - name: trigger_runSh_2
    type: manifest
    steps:
      - IN: nginx_image

  - name: runSh_0
    type: runSh
    steps:
      - IN: trigger_runSh_0
      - TASK:
        - script: failing_it
        - script: echo "versionName=$BUILD_NUMBER" >> $JOB_STATE/runSh_0.env
        - script: echo "hello there"

  - name: runSh_failed_pinnedVersion
    type: runSh
    steps:
      - IN: trigger_runSh_1
      - IN: runSh_0
      - TASK:
        - script: sleep 60

  - name: runSh_success_pinnedVersion
    type: runSh
    steps:
      - IN: trigger_runSh_1
      - IN: runSh_0
      - TASK:
        - script: sleep 60

  - name: runSh_unpinnedVersion
    type: runSh
    steps:
      - IN: trigger_runSh_1
      - IN: runSh_0
      - TASK:
        - script: sleep 60

  - name: runSh_2
    type: runSh
    steps:
      - IN: trigger_runSh_2
      - IN: runSh_1
      - TASK:
        - script: sleep 60
